### ISSUE TITLE
简历样式

### ISSUE THREAD

**Issue by watsonnnnn** [react-love/react-latest-framework#1]
想知道简历这么酷炫 有现成的组件么。。

**Comment by hyy1115** [comment]
这哪有简历？

**Comment by watsonnnnn** [comment]
https://hyy1115.github.io/huangyongyue/ 就是这个下面的啦~ 很酷的样子

**Comment by hyy1115** [comment]
这个问题我可以回答你，但是你不应该跑这个issue上来问，没什么组件，就是用一个html+css5+js强制写出来的。
