### ISSUE TITLE
请问一下我把你的代码clone下来后，运行项目然后更改代码。控制台显示热更新信息，可以页面却没有更新

### ISSUE THREAD

**Issue by yourenA** [react-love/react-latest-framework#13]
如题，请问一下事怎么回事？

**Comment by hyy1115** [comment]
支持src目录下面文件的热更新，在浏览器打开之后，可以在network里面看到开启了websocket连接。

**Comment by yourenA** [comment]
@hyy1115 控制台显示热更新了，但是页面却没有更新，要按一下F5修改的内容才出现

**Comment by hyy1115** [comment]
你的编辑器是什么？

**Comment by yourenA** [comment]
webstorm,在windows上

**Comment by yourenA** [comment]
![Uploading change.png…
![change](https://cloud.githubusercontent.com/assets/20793819/26303295/d0264622-3f19-11e7-8115-cc610fd84dee.png)
]()

**Comment by yourenA** [comment]
![change](https://cloud.githubusercontent.com/assets/20793819/26303343/f9678a14-3f19-11e7-985d-d39cfd997ba7.png)

**Comment by hyy1115** [comment]
webstorm要设置一下

preference => Debugger

然后将can accept external connections打钩

**Comment by yourenA** [comment]
@hyy1115 你好，我这样设置了还是不行。感觉应该不是编辑器的问题

**Comment by hyy1115** [comment]
用其他编辑器打开文件编辑试试，我不认为热更新跟系统有关系

**Comment by yourenA** [comment]
我使用sublime和换FF浏览器也还是这种情况

**Comment by hyy1115** [comment]
有其他电脑的话，可以在其他电脑上试试，window上面是否都有这种问题

**Comment by hyy1115** [comment]
不同的编辑器禁用了安全写入功能，需要手动开启：

Sublime Text 3 - 在用户首选项（user preference）中增加 "atomic_save": false。
IntelliJ - 在首选项（preferences）中使用搜索查找到 “safe write”并且禁用它。
Vim - 在您的设置（settings）中增加 :set backupcopy=yes。
WebStorm - 在 Preferences > Appearance & Behavior > System Settings 中取消选中 Use "safe write"。
