### ISSUE TITLE
package.js中引用了很多的依赖包，但有很多没用到

### ISSUE THREAD

**Issue by zhengjunxiang** [react-love/react-latest-framework#15]
就像redux-promise，react-hot-loader，postcss-loader，precss这些好像没在项目中用到；
希望作者能用react-hot-loader3替换掉react-transform-hmr，把postcss-loader用起来，谢谢；

**Comment by hyy1115** [comment]
这些是我在使用webpack1的时候遗留的依赖包，现在没有引用，是因为已经不需要了，使用一个东西，首先就需要了解他能用来做什么。

redux-promise：支持async/await实现action，目前已经使用babel实现，所以不再需要。

react-hot-loader：支持js或者jsx热更新，存在一定的bug，即使是v3，也不是最好的方案，而webpack2已结支持配置整个项目的热更新，这也是我目前用到的，所以弃用了react-hot-loader。

postcss-loader：已经在webpack中配置了。

precss：因为已经使用了less，就不再需要支持precss了。

开发环境如何配置，需要什么插件，取决于当前的功能是不是足够你的使用，如果不够，那么自行添加，如果够，那么没必要添加额外的配置，要知道，依赖越多，热更新就会越卡，谁都不希望开发过程中热更新卡爆。
在打包发布的时候，减少依赖包可以有效的降低打包后的js体积。

**Comment by zhengjunxiang** [comment]
嗯，多谢你耐心的回答 👍
