### ISSUE TITLE
windows下有个坑，依赖的fsevents装不上

### ISSUE THREAD

**Issue by zentoLu** [react-love/react-latest-framework#17]
报错： Unsupported platform for fsevents@
1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"
})
https://github.com/npm/npm/issues/9204#issuecomment-216853959
查了一下是这个包只有mac才有用，上面有解决方案

**Comment by hyy1115** [comment]
这不应该是一个warning吗？跟error还是有区别的，如果是error，整个npm就不能用了。
