### ISSUE TITLE
环境问题请教

### ISSUE THREAD

**Issue by joecfan** [react-love/react-latest-framework#18]
当前运行环境： development
http://localhost:3011
webpack built 420bf843335bfe5ad887 in 20156ms
有两问题请教：
1.请问编译后的文件放在哪里的，我看指定的是build目录，但是又找不到
2.改了代码之后，一般会自动编译，然后浏览器刷新，是没有配置还是我这里有问题？

**Comment by hyy1115** [comment]
你说的是执行npm start的时候，没生成静态文件，这个是可以生成到根目录下面显示，但是没什么必要。

如果你想看编译后的文件，执行npm run build-mac或者npm run build-win。

**Comment by joecfan** [comment]
根目录的哪个文件呢，build我也试过，但是似乎没看到啊。
还有怎么设置源代码更新保存后，浏览器自动页面刷新呢？
我看你用的是redux,请问感觉比flux复杂不少，这两个你是怎么考虑的？

谢谢，麻烦回答三个问题，帮我解下惑，非常感谢！

**Comment by hyy1115** [comment]
1、![image](https://cloud.githubusercontent.com/assets/9842036/26615370/e832973a-45f8-11e7-8f47-a4244ac535e4.png)

2、本项目支持热更新

3、没用过flux，不能比较两者。redux用习惯就不复杂，他本身是针对复杂的场景来解决问题，简单场景使用react组件内的state结合session就能完成

**Comment by joecfan** [comment]
感谢啊！
我看你一直都在更新项目，项目运行展现给我的就是那个页面，请问项目有什么特性呢

**Comment by hyy1115** [comment]
页面少，代码少，容易新增，容易删除，适合练习，适合开发。
