### ISSUE TITLE
Linux ubuntu Error

### ISSUE THREAD

**Issue by hellereye** [react-love/react-latest-framework#2]
ERROR in ./src/containers/Home/homeContainer.js
Module not found: Error: Can't resolve 'components/Home/Special' in '/home/fanfree/dev/boilerplate/react-redux-webpack/src/containers/Home'
 @ ./src/containers/Home/homeContainer.js 49:15-49
 @ ./src/appContainer.js
 @ ./src/index.js
 @ multi webpack-hot-middleware/client?path=http://localhost:3011/__webpack_hmr&reload=true&noInfo=false&quiet=false babel-polyfill ./src/index

ERROR in ./~/babel-loader/lib!./src/containers/Search/searchContainer.js
Module not found: Error: Can't resolve 'components/Search/HotSearch' in '/home/fanfree/dev/boilerplate/react-redux-webpack/src/containers/Search'
 @ ./~/babel-loader/lib!./src/containers/Search/searchContainer.js 41:17-55
 @ ./~/bundle-loader?lazy!./src/containers/Search/searchContainer.js
 @ ./src/appContainer.js
 @ ./src/index.js
 @ multi webpack-hot-middleware/client?path=http://localhost:3011/__webpack_hmr&reload=true&noInfo=false&quiet=false babel-polyfill ./src/index

**Comment by hyy1115** [comment]
你这里是报路径错误，尝试使用其他路径写法试试
