### ISSUE TITLE
TypeError: Cannot assign to read only property 'getDisplayName' of object '#<Object>'

### ISSUE THREAD

**Issue by xiaoping6688** [react-love/react-latest-framework#23]
chrome 浏览器下 点搜索🔍  切换路由时报错，在safari下正常~

发现去掉 react-redux 的 connect 就不会报错，很奇怪。

**Comment by hyy1115** [comment]
能提供你的系统环境和浏览器版本号吗？我现在无法复现这个bug。

**Comment by xiaoping6688** [comment]
Mac Chrome v58.0.3029.110
Node v6.11.0

**Comment by xiaoping6688** [comment]
找到原因了，因为我chrome安装了[Egret Inspector]（一款H5游戏引擎的调试插件），它会往对象原型中注入一些方法，和[react-redux]中Object.assign时产生了冲突。。。[原因](http://react-china.org/t/react-redux-connect-chrome/13365)
