### ISSUE TITLE
没有找到server.js

### ISSUE THREAD

**Issue by ghost** [react-love/react-latest-framework#24]
启动报错：
`module not found: Error: Can't resolve 'loglevel' in '/Users/ykw/react/react-redux-webpack2/node_modules/webpack-dev-server/client`

**Comment by hyy1115** [comment]
能详细说说你做了哪些操作导致这个问题出现吗？我并没有使用到server.js。

**Comment by ghost** [comment]
`npm install` 之后 `npm start` 就报错了

**Comment by hyy1115** [comment]
关于这个bug，是webpack造成的。

详情前往[https://github.com/webpack/webpack-dev-server/issues/1000](https://github.com/webpack/webpack-dev-server/issues/1000)

**Comment by hyy1115** [comment]
fixed in webpack-dev-server@2.6.1

**Comment by ghost** [comment]
好的。多谢🙏 我的2.6.0
