### ISSUE TITLE
这个项目可以用于后台管理系统么？

### ISSUE THREAD

**Issue by ChiaJune** [react-love/react-latest-framework#26]
如题。最近要做一个后台管理系统，想用react+redux+react-router来开发

**Comment by hyy1115** [comment]
可以，同时你也可以自己添加ant-design等第三方UI库，如果是公司内部的后台的话，异步加载功能变得不是那么重要，去掉import()功能。

**Comment by ChiaJune** [comment]
好的，谢谢。我想问一下 如何进入 “前端江湖”的微信群？

**Comment by hyy1115** [comment]
加我微信，然后拉你进群，hyy5863
