### ISSUE TITLE
搜索页面搜索失败

### ISSUE THREAD

**Issue by demonhumen** [react-love/react-latest-framework#27]
打开页面提示如下：

`Failed to load resource: the server responded with a status of 404 (Not Found)`

操作搜索页面出现：
`vendor.js:41365 Warning: Hash history cannot PUSH the same path; a new entry will not be added to the history stack`

操作步骤：
cnpm install 后直接运行 cnpm run start

操作系统:
mac 10.12.6

**Comment by hyy1115** [comment]
不太明白你说的搜索失败是什么意思？我没有加搜索功能。
