### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by NiCools** [react-love/react-latest-framework#31]
@connect(
    state => ({...state.home}),
    dispatch => bindActionCreators({...home, ...global}, dispatch)
)这样写是什么意思？不是很明白

**Comment by hyy1115** [comment]
和下面这种写法是一样的：mapStateToProps对应state => ({...state.home}), mapDispatchToProps对应dispatch => bindActionCreators({...home, ...global}, dispatch)

```javascript
export default connect(mapStateToProps, mapDispatchToProps)(Home)
```

**Comment by NiCools** [comment]
明白了，谢谢
