### ISSUE TITLE
react-router   又没有类似vue-router  router-view的东西

### ISSUE THREAD

**Issue by Banlangenn** [react-love/react-latest-framework#35]
页面路由切换的时候，只有部分组件重新渲染，在 vue-router 中，可以通过 router-view 实现，
react  有没有什么办法... 路由切换 实现部分组件重新渲染

**Comment by hyy1115** [comment]
这种是嵌套路由的做法，react-router也支持，入口组件App.js就是嵌套类型的，具体使用前往react-router文档查看。
