### ISSUE TITLE
请问redux里面的store直接放在index里面是不是有点不清晰啊

### ISSUE THREAD

**Issue by yftan** [react-love/react-latest-framework#38]
初学者不太明白这种写法，还有就是最新版没有了booklist的跳转啦？

**Comment by hyy1115** [comment]
将公共的配置统一放到入口文件index.js管理，store的配置不多，不习惯的话也可以自己分离出来。
booklist页面没啥用，就去掉了。

**Comment by yftan** [comment]
哦哦，好的，谢谢啦~
