### ISSUE TITLE
ios移动端300ms延迟

### ISSUE THREAD

**Issue by jipings** [react-love/react-latest-framework#39]
react16.4以后版本，已经合成的点击等事件，解决了这一问题

**Comment by hyy1115** [comment]
> react16.4以后版本，已经合成的点击等事件，解决了这一问题

你可以提供一个该解决方案说明的链接吗？

**Comment by jipings** [comment]
https://www.npmjs.com/package/react-tap-event-plugin

这个包也是处理300ms延迟的，有简单的说明
下面这张图片是我在ios11版本手机上调试的，请忽略标记，看click事件
<img src="https://raw.githubusercontent.com/jipings/baseStudy/master/img/click.png" />
-

**Comment by jipings** [comment]
https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away

**Comment by hyy1115** [comment]
@jipings 所以，现在新版本的react已经不需要插件来处理tap了，是吧。

**Comment by jipings** [comment]
As of Chrome 32 (back in 2014) this delay is gone for mobile-optimised sites, without removing pinch-zooming! Firefox and IE/Edge did the same shortly afterwards, and in March 2016 a similar fix landed in iOS 9.3.
不好意思，之前资料查看的不够仔细，这个问题是浏览器修复的，react16.4合成事件也对react-tap-event-plugin造成了影响（官方也说明了不适用react16.4以及以上的版本）.
react-fastclick也做了类似问题的说明
https://github.com/JakeSidSmith/react-fastclick/issues/61

**Comment by hyy1115** [comment]
@jipings ios端呢？

**Comment by jipings** [comment]
iOS 9.3以下版本就要考虑这个问题了（react版本也要考虑了），所以业务需求吧

> 元旦快乐
