### ISSUE TITLE
把你的项目直接down下来，打包之后，却发现体积很大

### ISSUE THREAD

**Issue by aiyuekuang** [react-love/react-latest-framework#5]
app.js这个文件的体积就达到了1.7M，那要是项目大了的话，这个打包的体积是不是会几M甚至几十M，这个该怎么解决？

**Comment by hyy1115** [comment]
能把你打包打印出来的信息贴出来吗？我刚测试打包之后是467kb。

当前运行环境： production
Hash: 7192c9f5721a24d4eeb7                                                    / Version: webpack 2.3.3
Time: 20253ms
         Asset       Size  Chunks                    Chunk Names
       
        app.js     467 kB       0  [emitted]  [big]  app

**Comment by aiyuekuang** [comment]
Hash: 11363a974533b0ff02c0
Version: webpack 2.4.1
Time: 10945ms
         Asset       Size  Chunks                    Chunk Names
1vKGKi36qI.png    2.37 kB          [emitted]
2Z8lgNdoQ0.png    2.81 kB          [emitted]
1K5Q2QEgAU.png    1.65 kB          [emitted]
1L8amFnjuF.png    1.87 kB          [emitted]
340D5JMtuU.png    3.16 kB          [emitted]
2iz_NxbRkS.png    2.03 kB          [emitted]
3z2ACjwE2-.png    2.62 kB          [emitted]
CbYCCEpfVQ.png    1.94 kB          [emitted]
wBKsOaAx2R.png    1.59 kB          [emitted]
M-0ZdUUVyt.jpg     149 kB          [emitted]
3bsS682P06.jpg    28.2 kB          [emitted]
2AYAHGCDwy.png  702 bytes          [emitted]
22GwDn0AM0.png  771 bytes          [emitted]
          0.js    17.2 kB       0  [emitted]
          1.js    3.85 kB       1  [emitted]
        app.js    1.88 MB       2  [emitted]  [big]  app

**Comment by hyy1115** [comment]
推荐你下载“动画版”打包测试一下。
你这个应该是标准版的，这个问题我得排查一下，可以的话说一下你的系统型号。

**Comment by aiyuekuang** [comment]
我的是win10的电脑

**Comment by hyy1115** [comment]
你执行的是 npm run build-win 吗？

**Comment by aiyuekuang** [comment]
是的

**Comment by hyy1115** [comment]
这有点麻烦，我身边没有windows系统，你在webpack.config文件里面打印一下process.env.NODE_ENV

console.log('运行环境：', process.env.NODE_ENV)

如果打印结果是production，那么打包就应该是正常的，如果是development，打包就是你现在的1M多的情况。

**Comment by aiyuekuang** [comment]
对了，我想起来了，isPro无论是“production”还是“development”永远都是false，不知道这是为什么

**Comment by aiyuekuang** [comment]
我的node应该是最新版的，不知道是不是这个原因

**Comment by aiyuekuang** [comment]
我甚至这样写：const isPro = 'production' === 'production';    最后还是打印的false，我就没辙了

**Comment by hyy1115** [comment]
说明package.json里面的set NODE_ENV=production没有起作用。

我用的也是node7.4.0版本，可能的情况是node环境没有配置好。

**Comment by aiyuekuang** [comment]
是的，这个不知道为什么不起作用

**Comment by hyy1115** [comment]
你换别人的电脑build一下，先排查出问题

**Comment by aiyuekuang** [comment]
我找到问题所在了production后面不能有空格，"build": "set NODE_ENV=production&& webpack --progress --config webpack.config.js"这样

**Comment by hyy1115** [comment]
ok，感谢你的火眼金睛，我这边也修改一下。

**Comment by aiyuekuang** [comment]
嗯，已star，多更新，等着跟你学习

**Comment by hyy1115** [comment]
等着你多反馈bug。
