### ISSUE TITLE
请教一下，DefinePlugin这个插件的具体作用是什么？

### ISSUE THREAD

**Issue by aiyuekuang** [react-love/react-latest-framework#6]
我百度了一下，没有看的太明白，所以还是想找你请教一下

**Comment by hyy1115** [comment]
设置全局变量，node服务器的环境变量传递不到前端，那么可以通过webpack的DefinePlugin方式将启动的node服务器环境变量传递给前端代码。
new webpack.DefinePlugin({
          'process.env':{
              'NODE_ENV': JSON.stringify(nodeEnv) //nodeEnv来自于package.json中script的配置。
          }
      }),
如上设置了process.env这个变量可以在前端项目直接读取到（前提是开启了webpack服务器）；
还可以设置其他全局变量给前端，比如我项目中写的全局url路径。
new webpack.DefinePlugin({
          BASE_URL: JSON.stringify('http://localhost:9009')
      }),
在项目的js文件中可以读取到该变量。

**Comment by aiyuekuang** [comment]
前端项目，指的是src里面的js文件能读取到吗？但是我没有看到你的项目里面用BASE_URL，或者说，这个体现在哪里？

**Comment by hyy1115** [comment]
比如有时候，你可能需要在component中获取当前运行的环境，是production还是development，那么可以在组件中直接读取provess.env.NODE_ENV这个全局变量。

我做过这样一个需求，我需要将build之后的bundle.js包含一个判断，如果是生产环境，就渲染一段jsx，如果是开发环境，渲染另外一段jsx，那么使用DefinePlugin来设置这个变量是非常好的选择。

**Comment by aiyuekuang** [comment]
嗯，大概明白了，但是没看到你在项目中用到

**Comment by hyy1115** [comment]
在utils文件夹的fetchData.js里面，被我注释了。

**Comment by aiyuekuang** [comment]
嗯，get请求的跨域可以，想问下post的请求，跨域可以实现吗？

**Comment by hyy1115** [comment]
你这个已经不属于issue了，违反社区规定的提问。

跨域怎么实现去网上搜索。
