### ISSUE TITLE
我打包之后部署到服务器为什么会报这个错？

### ISSUE THREAD

**Issue by aiyuekuang** [react-love/react-latest-framework#7]
app.js:20 Uncaught Error: [HMR] Hot Module Replacement is disabled.(anonymous function) @ app.js:20(anonymous function) @ app.js:20e @ app.js:1(anonymous function) @ app.js:20(anonymous function) @ app.js:20e @ app.js:1(anonymous function) @ app.js:20e @ app.js:1(anonymous function) @ app.js:1(anonymous function) @ app.js:1
localhost:3011/__webpack_hmr:1 GET http://localhost:3011/__webpack_hmr

**Comment by hyy1115** [comment]
打包出来的静态文件，热更新要禁用掉，我在webpack配置里面已经设置了development模式才开启热更新，不知道你是不是自己修改了什么。
