### ISSUE TITLE
在appContainer.js里componentDidMount下Search(() => {})的作用

### ISSUE THREAD

**Issue by cyqasim** [react-love/react-latest-framework#9]
不懂这个方法有什么作用，也没执行到这个方法

**Comment by hyy1115** [comment]
有关懒加载的理念。
1、请求相关路由时再懒加载当前js；
2、在首页初始化完成后，异步懒加载js。

在appContainer 的 componentDidMount中执行Search()方法去懒加载search组件，就是第2种方法。
